services:
  app:
    image: geo-intellect-1
    pull_policy: never
    container_name: my-python-app
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:17.0
    restart: always
    container_name: my-postgres
    env_file:
      - ./postgres/.env
    ports:
      - "8001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
